### ISSUE TITLE
Sorry, newbie here … a few basic questions

### ISSUE THREAD

**Issue by nullbreached** [unreality/FujiHK#1]
I apologize if it’s not correct protocol for even posting such questions under ‘issues’. I was excited to see this project but it will push my lack of skills around coding and even basic electronics to the limit. Before I even attempt any of it (even though I have purchased the basic components already, LOL) can anyone let me know whether it will work with my setup? I have a Fujitsu 208737 heat pump. It already has an a WLAN adapter which works with FGLair app on iOS. The step that is of greatest concern to me is ‘Connect the M5Atom to the AirConditioner via the 3-wire interface (see example circuit) or via the com connector on the indoor unit (will need a logic level converter)‘. Any clarification around that (assuming that it’s even applicable to my setup) would be appreciated.

**Comment by unreality** [comment]
Looks like the FGLair adapter requires dedicated access to your indoor unit (https://www.manualslib.com/manual/1631266/Fujitsu-Uty-Tfnxz1.html?page=13#manual), so to use this project you would need to remove your FGlair unit, and replace it with the m5atom.

An alternative in your case may be to set up homebridge and utilise one of the fglair plugins (eg https://github.com/smithersDBQ/homebridge-fujitsu i think?)

Another alternative is to write your own plugin or implementation that uses the FGLair API to control the AC.

If you want to proceed using this project, if you rip off your FGLair unit from the wall you should find the 3-wire interface talked about in the readme. Be sure to edit the source so that the M5Atom attempts to register as a Primary controller as well.

**Comment by nullbreached** [comment]
I really appreciate the thorough and quick response. Although I feel like I checked for plug-in availability some time ago, I think I presumed the plug-ins you suggested wouldn’t be compatible since they often mention ‘Fujitsu Split Mini’ which I assumed was a very particular model. but to my surprise it worked. I am a bit disappointed the more extensive project involving your plugin mighht not be something I pursue at this point as a result.
